### ISSUE TITLE
EPE performance on the flying chairs dataset

### ISSUE THREAD

**Issue by jytime** [princeton-vl/RAFT#1]
Hi Zach,

Thanks for your excellent work. The provided pretrained models have been trained on both the chairs and thing3D dataset. It is quicker to validate ideas on the chairs dataset. I was wondering if you may provide the RAFT model only pre-trained on the chairs dataset or its performance.

Best,
Jianyuan

**Comment by AojunZhou** [comment]
@jytime @zachteed Hi all, what about the EPE performance of RAFT model only using flyingchairs dataset?

**Comment by btwbtm** [comment]
~0.95 from my experience
