### ISSUE TITLE
Are those pretrained model trained on Sintel training split?

### ISSUE THREAD

**Issue by JiayuanSternLi** [princeton-vl/RAFT#10]
Hi, I am curious about what datasets those pretrained models are trained on. 
C+T?  C+T+S?

**Comment by zachteed** [comment]
Hi, the model chairs+things.pth is trained on FlyingChairs and FlyingThings3D (C+T). The model sintel.pth is the chairs+things.pth model  finetuned on Sintel (C+T+S).

**Comment by JiayuanSternLi** [comment]
Hi, how about the small?

**Comment by JiayuanSternLi** [comment]
> Hi, the model chairs+things.pth is trained on FlyingChairs and FlyingThings3D (C+T). The model sintel.pth is the chairs+things.pth model finetuned on Sintel (C+T+S).

Hi, how about the small.pth?

**Comment by zachteed** [comment]
small.pth is only trained on chairs + things
