### ISSUE TITLE
 UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`

### ISSUE THREAD

**Issue by jeffbaena** [princeton-vl/RAFT#104]
Dear authors @zachteed thanks for your great work.

referring to the error `lr_scheduler.step()` before `optimizer.step()`, I could not find where optimizer.step() is called.
in the file training.py from line 175 onwards I can find:
           

```
scaler.scale(loss).backward()
scaler.unscale_(optimizer)                
torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
            
scaler.step(optimizer)
scheduler.step()
scaler.update()
```

so the optimizer.step() does not seem to be called. Shall I modify the code somehow?

Many Thanks,
Stefano

**Comment by zachteed** [comment]
Hi Stefano,

optimizer.step() is called in scaler.step(optimizer) (https://pytorch.org/docs/stable/_modules/torch/cuda/amp/grad_scaler.html#GradScaler.step) so you shouldn't need to modify any code

**Comment by jeffbaena** [comment]
many thanks for your reply! your work is great and your repository is very well written, thanks again
