### ISSUE TITLE
Algorithm fail with identical frames

### ISSUE THREAD

**Issue by jbattab** [princeton-vl/RAFT#105]
Hi, we attempted your algorithm with 2 identical frames in the input makes the algorithm fails, it gives outputs that doesn't make sense, as opposed to DualTVL1OpticalFlow_create of cv2 which gives a black frame as output, are you aware of this?
Thanks.

**Comment by zachteed** [comment]
When I ran the model on couple pairs of identical frames I got an average flow mag of 0.03 pixels which seems correct to me. The visualization isn't designed you handle near-zero flow fields.
