### ISSUE TITLE
Implementation of the Efficient computation part differs from the paper

### ISSUE THREAD

**Issue by ProNoobLi** [princeton-vl/RAFT#11]
Hi, for the part of Efficient Computation for High-Resolution Images
![image](https://user-images.githubusercontent.com/33815430/83389401-c3db6480-a422-11ea-814d-5e264f0bc6a7.png)

It mentions that the level-based correlation should be done by half-pooling first and then matrix multiplication. However, in the code:
![image](https://user-images.githubusercontent.com/33815430/83389637-1e74c080-a423-11ea-8751-b595e51d9ec0.png)
![image](https://user-images.githubusercontent.com/33815430/83389660-27659200-a423-11ea-87ab-f20b2e8727f1.png)

You first calculate the correlation between two feature maps by full resolution. Let's say [384/8, 1024/8] = [48, 128]. After some fancy operations of reshape, view and matmul, then you got a [6144, 6144] cost volume.
Next, it uses avg_pool2d to downsample to get following levels.
Obviously, such calculation takes O(N^2) and opposite to your description of the paper. I am curious the reason for the difference. Is this code the early version that hasn't finished the efficient implementation?

**Comment by zachteed** [comment]
Hi, as described in our paper, this efficient computation is an "alternative implementation", which is unnecessary even for 1088x1920 videos. This code provides the default implementation that precomputes correlations of all pairs with complexity O(N^2).

**Comment by JiayuanSternLi** [comment]
> Hi, as described in our paper, this efficient computation is an "alternative implementation", which is unnecessary even for 1088x1920 videos. This code provides the default implementation that precomputes correlations of all pairs with complexity O(N^2).

Thank you, I am trying to reproduce the efficient way.
Additionally, the subscript of the cost volume should be (m-1) instead of m. Full resolution should be processed when m=1 without pooling, but the formula indicates the pooling 2*2 at level 1

**Comment by zachteed** [comment]
While the "efficent implementation" has lower complexity, it is generally much faster to precompute all pairs correlation. I've written a fairly optimized CUDA implementation of the "efficent" method (to confirm that the results are exactly the same), and it is still ~4x slower than the default implementation on Sintel resolution images, due to the fact that memory lookups are irregular.

Regarding the formula, I was starting indexing at 0

**Comment by JiayuanSternLi** [comment]
> While the "efficent implementation" has lower complexity, it is generally much faster to precompute all pairs correlation. I've written a fairly optimized CUDA implementation of the "efficent" method (to confirm that the results are exactly the same), and it is still ~4x slower than the default implementation on Sintel resolution images, due to the fact that memory lookups are irregular.
> 
> Regarding the formula, I was starting indexing at 0

I see. Is it possible to achieve correlation in pure torch since no need to handle backward function?

But the index of your paper starts at 1, thus it is a bit of confused
