### ISSUE TITLE
Local neighborhood difference between paper and implementation

### ISSUE THREAD

**Issue by NicolasHug** [princeton-vl/RAFT#122]
In the paper the local neighborhood is defined as such:

![image](https://user-images.githubusercontent.com/1190450/141831745-9ab39752-203c-4b7f-b2e9-0e63db4a7d29.png)

Which corresponds to figure A below. However, looking at the code and the output shapes of the Correlation module, it looks like the neighborhood corresponds to figure B instead: with r=4, the entries in the output pyramid have shape (batch_size, H, W, 81) where 81 = (r * 2 + 1)^2

I'm wondering if this is a just a typo in the paper, or if there could be an unintended bug in the implementation? (Or I might just be missing something)
![neighb2](https://user-images.githubusercontent.com/1190450/141832626-538d29ec-8d76-4965-9afb-0bcecb80d87f.jpg)

**Comment by zachteed** [comment]
You are correct, it looks like there is a typo in the paper (l_1 norm should be l_inf norm).  The version implemented in the code (B) is correct.
