### ISSUE TITLE
question on augmentor image size

### ISSUE THREAD

**Issue by pichuang1984** [princeton-vl/RAFT#13]
Thanks for sharing your work. I have a question on the image size setting for the augmentor in FlyingChairs dataset. Why do you set the crop size(self.image_size) to be [368, 496]?

Thanks,

**Comment by zachteed** [comment]
There was really no reason behind that choice. I think I wanted there to be the possibility of downsampling during augmentations (since original resolutions were 384x512), but I didn't really do any experimenting with the crop size.
