### ISSUE TITLE
About the training dataset used.

### ISSUE THREAD

**Issue by HyeongminLEE** [princeton-vl/RAFT#131]
Hi, thank you for sharing a source code of good research.
Did you train the model with a total version of Flying Things 3D? or just the subset of Flying Things 3D as Flownet 2.0 did?

Thanks

**Comment by zachteed** [comment]
Hi, I used the full set, but either can be used. You can swap in a different dataloader if you would prefer to use the subetset. See here: https://github.com/princeton-vl/RAFT/issues/102
