### ISSUE TITLE
What metrics should we refer during training?

### ISSUE THREAD

**Issue by ProNoobLi** [princeton-vl/RAFT#14]
![image](https://user-images.githubusercontent.com/33815430/84458463-a5cdf980-ac97-11ea-83d2-79a0f59464b8.png)
![image](https://user-images.githubusercontent.com/33815430/84458492-b2eae880-ac97-11ea-95fd-859ae8b56bfa.png)
Hi, 
How can I explain the metrics during training? Or could you please provide a loss curve we can refer?
As I read your code, the metrics are divided into four parts. Average EPE over all pixels, average epe over pixels < 1pix; <3pix; <5pix. Based on my training records, the average epe over all; <1; <3 becomes larger at first and epe(<5pix) decreases. My understanding is that the pred_flow at first is not accurate and pretty large, thus <5 pix has a large number while small all epe  doesn't indicate a correct prediction, right??
Therefore, what value should we refer during training to check if it converges since optical flow is not like classification task which has a straightforward evaluation(accuracy).

**Comment by zachteed** [comment]
You probably want to use a validation split to track the training process. For reference, here are plots of the end-point-error using the chairs validation split, and when using Sintel (train) clean as the validation split (when training on FlyingChairs). Train converges to ~1.42px on chairs and ~2.40px on sintel.
![TrainingCurves](https://user-images.githubusercontent.com/11929093/84689415-ef744980-af0e-11ea-870b-adeb792fcf6d.png)
