### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ismeyueyue** [princeton-vl/RAFT#180]
When I run the demo test `python demo.py --model=models/raft-things.pth --path=demo-frames` on images with resolutions of [1, 3, 1440, 2560], it prompted me with a memory error `RuntimeError: CUDA out of memory.`, even though only a few frames of frames.

error msg:
```
Traceback (most recent call last):
  File "test_image.py", line 51, in <module>
    flow_low, flow_up = model(image1, image2, iters=20, test_mode=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/raft-opticalflow/core/raft.py", line 107, in forward
    corr_fn = CorrBlock(fmap1, fmap2, radius=self.args.corr_radius)
  File "/workspace/raft-opticalflow/core/corr.py", line 19, in __init__
    corr = CorrBlock.corr(fmap1, fmap2)
  File "/workspace/raft-opticalflow/core/corr.py", line 60, in corr
    return corr  / torch.sqrt(torch.tensor(dim).float())
RuntimeError: CUDA out of memory. Tried to allocate 12.36 GiB (GPU 0; 23.65 GiB total capacity; 12.65 GiB already allocated; 8.50 GiB free; 13.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by hajoxs** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 59.41 GiB (GPU 0; 6.00 GiB total capacity; 636.69 MiB already allocated; 2.60 GiB free; 1.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


I'm also experiencing this problem and would like to know if you've resolved it yet

**Comment by hajoxs** [comment]
Thank you for your help
