### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by llesky** [princeton-vl/RAFT#19]
Hi, Thanks for sharing the work. I have a question about the training dataset.
1. In the paper, "C+T+S+K+H" is a combination of KITTI, HD1K, and Sintel data when finetuning on Sintel. However, the code shows it's a combination of  KITTI, HD1K, Sintel, and **3Dthings**. C+T+ S/K also includes **3Dthings**. Is there some mistake in code?

**Comment by zachteed** [comment]
Flyingthings3d is used when finetuning on Sintel, similar to VCN. See Appendix C in our paper.

**Comment by llesky** [comment]
I see, Thanks
