### ISSUE TITLE
Schematic + minor bug

### ISSUE THREAD

**Issue by tomas2211** [princeton-vl/RAFT#2]
Hi!
Nice work, I especially appreciate the code clarity.
I just created a schematic of RAFT in drawio and wanted to share:
https://drive.google.com/file/d/1R9NeeKfHLCyMm6S7wH8sAjvI98Sc7sDg/view?usp=sharing
If you find any mistakes or have suggestions to make it more clear please tell me.

Also, just a minor bug - I think when constructing the correlation pyramid:
https://github.com/princeton-vl/RAFT/blob/559176d42bbc6c3ae8498b40ccf6fce4e041876e/core/modules/corr.py#L18
you meant to write
```python
for i in range(self.num_levels - 1):
```
as currently the code constructs one extra level that is not used.

Have a nice day,
Tomas

**Comment by zachteed** [comment]
Hi Thomas, looks like your right, I was accidentally constructing an extra level, thanks! Your diagram looks good
