### ISSUE TITLE
Efficient Cost Computation for High Resolution Images

### ISSUE THREAD

**Issue by jytime** [princeton-vl/RAFT#20]
Hi Zachary,

In the paper section 3.2, an alternative cost computation method is mentioned, which scales O(NM). I was wondering is this implementation provided in the repository?

Best,
Jianyuan

**Comment by zachteed** [comment]
Hi Jianyuan,

This is some Python code for the "efficient implementation", you can plug it in instead of the default CorrBlock; however, it is much slower than the default all-pairs.

```
class CorrBlock:
    def __init__(self, fmap1, fmap2, num_levels=4, radius=4):
        self.num_levels = num_levels
        self.radius = radius
        self.corr_pyramid = []

        self.fmap1 = fmap1
        self.fmap2 = fmap2

    def corr(self, fmap1, fmap2, coords):

        B, D, H, W = fmap2.shape
        fmap1 = fmap1.unsqueeze(dim=-1)
        fmap2 = fmap2.unsqueeze(dim=-1)

        # map grid coordinates to [-1,1]
        xgrid, ygrid = coords.split([1,1], dim=-1)
        xgrid = 2*xgrid/(W-1) - 1
        ygrid = 2*ygrid/(H-1) - 1
        zgrid = torch.zeros_like(xgrid) - 1
        grid = torch.cat([zgrid, xgrid, ygrid], dim=-1)

        fmapw = F.grid_sample(fmap2, grid, align_corners=True)

        corr = torch.sum(fmap1*fmapw, dim=1)
        return corr / torch.sqrt(torch.tensor(D).float())

    def __call__(self, coords):

        r = self.radius
        coords = coords.permute(0, 2, 3, 1)
        batch, h1, w1, _ = coords.shape

        fmap1 = self.fmap1
        fmap2 = self.fmap2

        out_pyramid = []
        for i in range(self.num_levels):
            dx = torch.linspace(-r, r, 2*r+1)
            dy = torch.linspace(-r, r, 2*r+1)
            delta = torch.stack(torch.meshgrid(dy, dx), axis=-1).to(coords.device)

            centroid_lvl = coords.reshape(batch, h1, w1, 1, 2) / 2**i
            coords_lvl = centroid_lvl + delta.view(-1, 2)

            corr = self.corr(fmap1, fmap2, coords_lvl)
            fmap2 = F.avg_pool2d(fmap2, 2, stride=2)
            out_pyramid.append(corr)

        out = torch.cat(out_pyramid, dim=-1)
        return out.permute(0, 3, 1, 2).contiguous().float()
```

**Comment by jytime** [comment]
Thanks for your quick reply. Just a small note that fmap1 may be also downsampled to fit the size fmap2, as in `fmap2 = F.avg_pool2d(fmap2, 2, stride=2)`.

**Comment by zachteed** [comment]
Actually, fmap1 needs to stay at full resolution, otherwise the entries of out_pyramid will be different sizes, and cannot be concatenated.

**Comment by leeqiaogithub** [comment]
> Hi Jianyuan,
> 
> This is some Python code for the "efficient implementation", you can plug it in instead of the default CorrBlock; however, it is much slower than the default all-pairs.
> 
> ```
> class CorrBlock:
>     def __init__(self, fmap1, fmap2, num_levels=4, radius=4):
>         self.num_levels = num_levels
>         self.radius = radius
>         self.corr_pyramid = []
> 
>         self.fmap1 = fmap1
>         self.fmap2 = fmap2
> 
>     def corr(self, fmap1, fmap2, coords):
> 
>         B, D, H, W = fmap2.shape
>         fmap1 = fmap1.unsqueeze(dim=-1)
>         fmap2 = fmap2.unsqueeze(dim=-1)
> 
>         # map grid coordinates to [-1,1]
>         xgrid, ygrid = coords.split([1,1], dim=-1)
>         xgrid = 2*xgrid/(W-1) - 1
>         ygrid = 2*ygrid/(H-1) - 1
>         zgrid = torch.zeros_like(xgrid) - 1
>         grid = torch.cat([zgrid, xgrid, ygrid], dim=-1)
> 
>         fmapw = F.grid_sample(fmap2, grid, align_corners=True)
> 
>         corr = torch.sum(fmap1*fmapw, dim=1)
>         return corr / torch.sqrt(torch.tensor(D).float())
> 
>     def __call__(self, coords):
> 
>         r = self.radius
>         coords = coords.permute(0, 2, 3, 1)
>         batch, h1, w1, _ = coords.shape
> 
>         fmap1 = self.fmap1
>         fmap2 = self.fmap2
> 
>         out_pyramid = []
>         for i in range(self.num_levels):
>             dx = torch.linspace(-r, r, 2*r+1)
>             dy = torch.linspace(-r, r, 2*r+1)
>             delta = torch.stack(torch.meshgrid(dy, dx), axis=-1).to(coords.device)
> 
>             centroid_lvl = coords.reshape(batch, h1, w1, 1, 2) / 2**i
>             coords_lvl = centroid_lvl + delta.view(-1, 2)
> 
>             corr = self.corr(fmap1, fmap2, coords_lvl)
>             fmap2 = F.avg_pool2d(fmap2, 2, stride=2)
>             out_pyramid.append(corr)
> 
>         out = torch.cat(out_pyramid, dim=-1)
>         return out.permute(0, 3, 1, 2).contiguous().float()
> ```

I wonder why 5D grid-sample is used here, is it necessary?
