### ISSUE TITLE
Why scale mask by 0.25 to balance gradients?

### ISSUE THREAD

**Issue by complexfilter** [princeton-vl/RAFT#24]
Hi Zachary:

   I read you code in update block. 

`    mask = .25 * self.mask(net)`

It mentions that it uses scale mask to balance gradients. I wonder what is the rationale for you to choose 0.25 for the upsampling by 8 scenario. What would you choose if you were to do upsampling by 2 and 4.

Thanks!

**Comment by zachteed** [comment]
Hi, this was just for initialization and doesn't have anything to do with the up-sampling resolution.  It can probably be removed (assuming the model is trained without).
