### ISSUE TITLE
Inference Time

### ISSUE THREAD

**Issue by WangDeyao** [princeton-vl/RAFT#27]
Hi

Congratulations on winning the best paper award!

In the paper it is mentioned that the inference time of RAFT is around 100 ms. I want to ask what is the image size you are using? Also, which tool are you using to test the inference time?

Thanks

**Comment by zachteed** [comment]
Hi, thanks! I timed on Sintel resolutions (1080x436) for 10 iterations on a 1080Ti.  I used a torch.cuda.Event block for timing, and did some additional optimizations such setting cudnn.benchmark to True, and only performed upsampling at the last iteration.

**Comment by ankushpanwar19** [comment]
I am using the pretrained "raft-small" model for prediction and it is takes around 2-3 seconds for flow prediction. I have set Iterations=10 on GeForce GTX 1080 Ti. Could you please help me to reduce the inference time? Or suggest some changes.
Image resolution :(1080x480)
