### ISSUE TITLE
about up mask

### ISSUE THREAD

**Issue by Maxzheng-tect** [princeton-vl/RAFT#29]
Hi! first at all, thank you so much for sharing this work.
Actually, we can do upsample predictions after all iters.

**Comment by zachteed** [comment]
Hi, I'm not sure I understand your question. If you run with test_mode=True, only the last flow field is upsampled. If test_mode=False, then it will return all usampled intermediate predictions.

**Comment by Maxzheng-tect** [comment]
> Hi, I'm not sure I understand your question. If you run with test_mode=True, only the last flow field is upsampled. If test_mode=False, then it will return all usampled intermediate predictions.

Hi, 

> Hi, I'm not sure I understand your question. If you run with test_mode=True, only the last flow field is upsampled. If test_mode=False, then it will return all usampled intermediate predictions.

Hi! thanks for your reply! Yes, I run with test_mode=True. I got it, thanks.
