### ISSUE TITLE
Which of the released model is more suitable for real-world videos

### ISSUE THREAD

**Issue by Robert-BoMiao** [princeton-vl/RAFT#30]
Hi,

I want to use your model as an optical flow extractor on real-world videos. May I know which of the released model is more suitable?

Thanks!

**Comment by zachteed** [comment]
I would recommend trying both the sintel.pth model and the things.pth model. My guess would be sintel.pth since it is trained on the largest number of dataset.

**Comment by Robert-BoMiao** [comment]
> I would recommend trying both the sintel.pth model and the things.pth model. My guess would be sintel.pth since it is trained on the largest number of dataset.

Thanks for your suggestion!
