### ISSUE TITLE
Why do you use batch normalization in context encoder?

### ISSUE THREAD

**Issue by liuppboy** [princeton-vl/RAFT#31]
Hi, this is a very nice work! Thanks for your contribution!

In your paper, you use instance normalization in feature encoder, but batch normalization in context encoder. But in the code, I find that BN is freezed after training on [chairs](https://github.com/princeton-vl/RAFT/blob/13198c355d11c3a0c45f09d1f15ead4b81a5043f/train.py#L148). In this case, I am confuse why you do not use instance normalization in both feature encoder and context encoder? Or may be we can share feature encoder and context encoder, which can further recude the parameters.

**Comment by zachteed** [comment]
I didn't find the type of normalization in the context encoder to matter much (though I didn't try instance norm). The team that submitted RAFT-TF_RVC to the robust vision challenge removed normalization from the context encoder entirely.
