### ISSUE TITLE
How to deal with the DataParallel imbalanced memory usage problem?

### ISSUE THREAD

**Issue by sunnyday2017** [princeton-vl/RAFT#33]
Hi, I am very interested in your work and try to train your model using your training scheme. But when using FlyingChairs as the training dataset, the maximum batch size I can set is 5 no matter I use 1 2080Ti GPU or 2 2080Ti GPUs because of the DataParallel imbalanced memory usage.  May you tell me how to deal with this problem?

**Comment by zachteed** [comment]
Make sure both GPUs are visible to PyTorch. `torch.cuda.device_count()` should give you 2 if you are training with 2 GPUs

**Comment by sunnyday2017** [comment]
Yes, both GPUs are visible to PyTorch. When I set batch size = 4, GPU = 0,1, the memory usage is:

 GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0  On |                  N/A |
| 27%   36C    P2   211W / 250W |   8382MiB / 11016MiB |     76%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 27%   35C    P2   201W / 250W |   4855MiB / 11019MiB |     72%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

The GPU memory usage of GPU 0 is much larger than the usage of GPU 1. I found that many people have encountered this problem because DataParallel in PyTorch puts more data on GPU 0, but I did not find a good solution. You used DataParallel in your code. Have you encountered this imbalanced memory usage problem?

**Comment by zachteed** [comment]
That seems strange, I haven't experienced this issue with DataParallel before.  All our models where trained using `train_standard.sh` on 2 x 2080Ti,

You could look into using DistributedDataParallel, or `./train_mixed` which uses only a single gpu.

**Comment by sunnyday2017** [comment]
Thanks for your reply! I will try DistributedDataParallel. 
And thank you for proving such a neat and concise code for optical flow estimation!
