### ISSUE TITLE
Memory issue with one GPU at inference time - process gets killed

### ISSUE THREAD

**Issue by farnaznouraei** [princeton-vl/RAFT#35]
Hi, thanks for the nice work!

I am testing RAFT on Epic Kitchens and even though I limited the number of frames processed to 300 and I am using --alternate_corr flag, the python process gets killed after a certain point, with no warnings or messages (only says "killed"). Interestingly, when I limit the frames to 100 it works fine.

I was wondering if anyone has had the same problem and how they resolved it. I only have one GPU available and more inference time is okay with me.

Thanks!

**Comment by zachteed** [comment]
Are you running the `demo.py` script?  I think by default, it loads all images into memory at once.

Instead, you should load pairs of frames one at a time, like what is done in `evaluate.py`

**Comment by farnaznouraei** [comment]
Thanks a lot for your help! I modified it as done in evaluate.py and it works perfectly with no need for --alternate_corr!
Closing the issue now.
