### ISSUE TITLE
A consultation on the use of RAFT

### ISSUE THREAD

**Issue by Starboy-at-earth** [princeton-vl/RAFT#36]
Dear author of RAFT:
         It is very nice that your work of RAFT has forwarded the optical flow estimation. Recently, I prepare to use this work to generate optical flow graphs for DAVIS 2016, which contains 50 short videos widely used to do video object segmentation. However, I am new to optical flow estimation and thus is a little puzzled by your provided demo.py and evaluate.py. I wanna know which .py file I should use to estimate DAVIS 2016.

**Comment by zachteed** [comment]
You will likely need to make some modifications for custom applications. RAFT takes two frames as input and estimates optical flow, see Line 67 in demo https://github.com/princeton-vl/RAFT/blob/13198c355d11c3a0c45f09d1f15ead4b81a5043f/demo.py#L67 

So you will need to load in pairs of frames which you want to estimation optical flow, then call the model on those pairs of frames
