### ISSUE TITLE
is the pretrained models provided same as papers?

### ISSUE THREAD

**Issue by oblime** [princeton-vl/RAFT#37]
Thank you for your excellent works on the optical flow. May I ask is the provided pretrained models same as the paper's description?
Based on the name, I would assume:
raft-chairs.pth: pretrained on FlyingChairs
raft-things.pth: pretrained on FlyingChairs + FlyingThings
raft-small.pth: smaller model pretrained on Chairs + Things
raft-kitti.pth: trained on C+T+K
raft-sintel.pth: trained on C+T+S
Is it right?

**Comment by zachteed** [comment]
Yes, except raft-kitti.pth and raft-sintel.pth follow the C+T+S+K+H training in the paper
