### ISSUE TITLE
What does '2-view' mean in the paper?

### ISSUE THREAD

**Issue by JohnnieXDU** [princeton-vl/RAFT#38]
Hi, thanks for sharing the excellent work!!

A quick question, could you please explain what does '**2-view**' means in the original paper **Table. I**? e.g. Ours (2-view). It seems there is no explanation in the paper and supplementary. 

Is that means stereo-setting? or just the normal model with 4.8M parameters (compared to the small model with 1M parameters)? 

Thanks!!

**Comment by zachteed** [comment]
Hi, it means two frames as input, as opposed to warp start which uses the full video
