### ISSUE TITLE
GPU Memory Usage

### ISSUE THREAD

**Issue by lhao0301** [princeton-vl/RAFT#39]
Thanks for your code!

How much gpu memory is used during inference with one 1080x1920 image? And how about the speed, ~500ms(100ms for 1036x482 -> 500ms for 1080x1920)?

**Comment by lhao0301** [comment]
A little gpu-consuming. 
Is there going to some optimization for this (more efficient, especially for high-resolution video, but with similar performance)?

**Comment by zachteed** [comment]
1080x1920 is extremely high resolution, for most applications it would probably be better to downsample by a factor of 2.

Using `--alternate-corr` will significantly reduce memory usage, but my current cuda implementation takes 2-3x longer than the default all pairs; however, I think with more optimization it should be able to run much faster.

One thing you can do is to replace Ln 60 with an inplace operator, that way the full correlation volume isn't copied
 https://github.com/princeton-vl/RAFT/blob/25eb2ac723c36865c636c9d1f497af8023981868/core/corr.py#L60

```return corr.mul_(1.0/torch.sqrt(torch.tensor(dim).float()))```

**Comment by lhao0301** [comment]
Okay. Thanks for your kind suggestions.
