### ISSUE TITLE
Question about the flow estimation.

### ISSUE THREAD

**Issue by MarioDuran** [princeton-vl/RAFT#4]
Hi! first at all, thank you so much for sharing this work, is really amazing!

I´m using this repo to generate an optic flow of a generical video, we are working on face anti spoofing techniques and we want to use an approach like this, but Im getting weird results which I do not know if they are normal, you can see the output here. 
https://drive.google.com/file/d/1-ALLjgPthC4P52F-V35dVDkTZq2EbQyN/view?usp=sharing

is this the normal output of this framework? it seems a little noisy, but I do not know if I messed up somewhere. 

this is the arguments I´m using, thanks in advance for any advice or suggestion!

parser.add_argument('--model', default = 'models/chairs+things.pth',  help="restore checkpoint")
parser.add_argument('--small', action='store_true', help='use small model')
parser.add_argument('--iters', type=int, default=50)

**Comment by zachteed** [comment]
Hi Mario,

I'm not able to open the video you attached. Could you possibly provide a link in different format or include a link to the original video?

**Comment by MarioDuran** [comment]
Hi! thanks again for your help, I uploaded the video to youtube, hope it helps to visualize it better.
https://youtu.be/qoSbfaX1PMA

thank you so much fin advance for your time!

**Comment by kwea123** [comment]
Some frames are good, some are noisy... If it's not due to bugs, I suspect that it's in some sort of adversarial attack. Can you also share the original color video?
