### ISSUE TITLE
A typo in Efficient Correlated layer 

### ISSUE THREAD

**Issue by hzhang57** [princeton-vl/RAFT#42]
https://github.com/princeton-vl/RAFT/blob/25eb2ac723c36865c636c9d1f497af8023981868/core/corr.py#L82
Hi, should the 0 here be i?

fmap1_i = self.pyramid[0][0].permute(0, 2, 3, 1).contiguous() --> fmap1_i = self.pyramid[i][0].permute(0, 2, 3, 1).contiguous()

**Comment by zachteed** [comment]
Hi, I believe the current implementation is correct. If you look the equation on page 7 of our paper, only the second feature my is pooled, fmap1 is not pooled

**Comment by hzhang57** [comment]
Thank you for detailed explanation, I miss understand the function.

**Comment by vadimkantorov** [comment]
Then probably `self.pyramid[i][0]` should not even be computed for `i > 0`?
