### ISSUE TITLE
DAVIS dataset

### ISSUE THREAD

**Issue by robintzeng** [princeton-vl/RAFT#44]
Hi, I want to use the DAVIS dataset as you mention in the paper 4.5.
I wonder which pretrain model did you use.
Also, should I modify the **evaluate.py** to load the **DAVIS dataset** ?

Thank you !!

**Comment by zachteed** [comment]
Hi, I modified the demo.py script so you should be able to use that for Davis.

Just run `python demo.py --model=models/raft-sintel.pth --path="path to davis image folder"`. Note the maximum size we ran at was 1080p, if you are using larger resolution video you may have to switch to the "alternate implementation" or downsize to 1080p

**Comment by robintzeng** [comment]
Thank you so much !
It works !
