### ISSUE TITLE
Input Image Pad Mode

### ISSUE THREAD

**Issue by lhao0301** [princeton-vl/RAFT#45]
A little curious about the image pad mode. 
The pad mode for kitti and other dataset(default is `sintel` mode) is different, why?
https://github.com/princeton-vl/RAFT/blob/d3f38401862ffa58dfb8b70b4be0179c40bd7f20/evaluate.py#L64
https://github.com/princeton-vl/RAFT/blob/d3f38401862ffa58dfb8b70b4be0179c40bd7f20/core/utils/utils.py#L16

**Comment by zachteed** [comment]
There isn't a particularly reason for this other than the fact that results were submitted to the KITTI and Sintel leaderboards with slightly different padding methods. Both are implemented for consistency with the submission results. This ends up making very little difference, either padding can be used in general.
