### ISSUE TITLE
Not really an issue, per se

### ISSUE THREAD

**Issue by ikanreed** [princeton-vl/RAFT#46]
But in core/utils/utils.py in InputPadder, you have a line that looks like

(((self.ht // 8) + 1) * 8 - self.ht) % 8

And I just want to say that that's mathematically equivalent to (-self.ht)%8, and yields the exact same result for all integers and floats.

**Comment by zachteed** [comment]
Hi, thanks for pointing this out, that looks much better. Not sure exactly what I was thinking with that expression. I'll update padder next time I make any updates to the repo.
