### ISSUE TITLE
flow_low ?

### ISSUE THREAD

**Issue by SharifElfouly** [princeton-vl/RAFT#48]
Hey, I'm a total noob at optical flow estimation and I don't understand what `flow_low` is. 
`
flow_low, flow_up = model(image1, image2, iters=20, test_mode=True)`
 
An explanation would be greatly appreciated.

**Comment by zachteed** [comment]
Hi, it is the estimation flow at 1/8 resolution before up-sampling. It is used when we perform warm-start initialization https://github.com/princeton-vl/RAFT/blob/d3f38401862ffa58dfb8b70b4be0179c40bd7f20/evaluate.py#L41
