### ISSUE TITLE
dataloader question when ./train_mixed.sh

### ISSUE THREAD

**Issue by zzl777** [princeton-vl/RAFT#49]
File "train.py", line 247, in <module>
    train(args)
  File "train.py", line 150, in train
    train_loader = datasets.fetch_dataloader(args)
  File "core/datasets.py", line 230, in fetch_dataloader
    train_loader = data.DataLoader(train_dataset, batch_size=args.batch_size, 
  File "/data/zzl/anaconda3/envs/raft/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/data/zzl/anaconda3/envs/raft/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 95, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by zachteed** [comment]
The dataloader isn't able to find the training dataset. Either use the directory structure in the Readme or change the dataset_path variable in datasets.py

**Comment by zzl777** [comment]
Thanks for answer.  I still have some questions: 1.Does the command (./train_mixed.sh) run only when the four datasets all in the directory? If I only have two datasets(such as Sintel and DAVIS), can I train the network? 2. If I want to train another dataset(my private dataset), what should I do?  Thanks!!!

**Comment by zachteed** [comment]
You can modify the function https://github.com/princeton-vl/RAFT/blob/d3f38401862ffa58dfb8b70b4be0179c40bd7f20/core/datasets.py#L199

to
```
 def fetch_dataloader(args, TRAIN_DS='C+T+K+S+H'):
       aug_params = {'crop_size': args.image_size, 'min_scale': -0.2, 'max_scale': 0.6, 'do_flip': True}
       sintel_clean = MpiSintel(aug_params, split='training', dstype='clean')
       sintel_final = MpiSintel(aug_params, split='training', dstype='final')
       train_dataset = sintel_clean + sintel_final
       train_loader = data.DataLoader(train_dataset, batch_size=args.batch_size, 
           pin_memory=False, shuffle=True, num_workers=4, drop_last=True)

      print('Training with %d image pairs' % len(train_dataset))
      return train_loader
```
to train only using sintel data. To train on another dataset, you will need to write your own subclass of FlowDataset

**Comment by zzl777** [comment]
Thanks again for your answer! I modified the function to train only using Sintel dataset. However, there exists another question during training:
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    train(args)
  File "train.py", line 192, in train
    results.update(evaluate.validate_chairs(model.module))
  File "/data/zzl/anaconda3/envs/raft/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/data/zzl/PycharmProjects/RAFT/evaluate.py", line 90, in validate_chairs
    epe = np.mean(np.concatenate(epe_list))
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
what should I do to address it? thanks a lot!

**Comment by zachteed** [comment]
In the training command, you need to change the flag to specify the validation dataset, from `--validation chairs' to `--validation sintel`

**Comment by zzl777** [comment]
Thanks again for your answer! If I want to save all the output flow images in a directory (just flow images, not an original frame on the top and a flow image on the below in the output of demo.py), what should I do? thanks a lot!
