### ISSUE TITLE
demo does not work

### ISSUE THREAD

**Issue by Pavelrst** [princeton-vl/RAFT#50]
I've been able to run the demo with a code from this commit: 559176d42bbc6c3ae8498b40ccf6fce4e041876e
But on the latest commit, when trying to run the demo I get this error:

Traceback (most recent call last):
  File ".../RAFT/demo.py", line 75, in <module>
    demo(args)
  File ".../RAFT/demo.py", line 44, in demo
    model.load_state_dict(torch.load(args.model))
  File "G:\Software\Anaconda\envs\scopeflow\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.update_block.mask.0.weight", "module.update_block.mask.0.bias", "module.update_block.mask.2.weight", "module.update_block.mask.2.bias".

**Comment by zachteed** [comment]
Try re-downloading the models, it seems like you might be using older models from the first version of this repo
I ran the demo with the command `python demo.py --model=models/raft-things.pth --path=demo-frames` but didn't get any issue

**Comment by zachteed** [comment]
I'm pretty sure this was the issue, feel free to re-open if this does not fix
