### ISSUE TITLE
Error while running the demo  - Possible OpenCV or PyQt issue

### ISSUE THREAD

**Issue by BarathwajAnandan** [princeton-vl/RAFT#58]
Hi,
I get this error while trying to run the demo. From the research I did, I think it's because of the opencv conflict or pyQt issue. But none of the solutions fixed it for me. Any help would be appreciated.

The flow is determined for the first frame and then I get this.

**QObject::moveToThread: Current thread (0x55c49e4f2fc0) is not the object's thread (0x55c49e68c8c0).
Cannot move to target thread (0x55c49e4f2fc0)**

**Comment by zachteed** [comment]
It seems like just a visualization error. You can uncomment the matplotlib visualization https://github.com/princeton-vl/RAFT/blob/d3f38401862ffa58dfb8b70b4be0179c40bd7f20/demo.py#L34 to use that instead of opencv
