### ISSUE TITLE
About Correlation Range

### ISSUE THREAD

**Issue by BB88Lee** [princeton-vl/RAFT#59]
Hi! first of all, thanks for sharing this great work.
I noticed, there is a term about  'Correlation Range' in ablation.
I didn't see the relevant code.
I'm very curious about the effect of 'Correlation Range'. Could you give me some suggestions on how to implement this term?

**Comment by zachteed** [comment]
Hi, unfortunately limiting the correlation range requires a custom cuda kernel, since the correlation can no longer be implemented as dense matrix multiplication. The current code doesn't include this functionality
