### ISSUE TITLE
Dropout never runs and if it does throws RuntimeError

### ISSUE THREAD

**Issue by irwinherrmann** [princeton-vl/RAFT#6]
Hi,

Thanks for sharing the code!

In this code, I think dropout will always be set to 0 by raft.py line [29.](https://github.com/princeton-vl/RAFT/blob/master/core/raft.py#L29) get_kwargs() returns a list of tuples:

[('batch_size', 2), ('clip', 1.0), ('corr_levels', 4), ('corr_radius', 4), ('dataset', 'sintel_1'), ('dropout', 0.2), ('epsilon', 1e-08), ('image_size', [368, 496]), ('iters', 12), ('lr', 2e-06), ('name', 'sintel1_do0'), ('num_steps', 1), ('restore_ckpt', None), ('small', False), ('wdecay', 5e-05)]

Then, the 'dropout' in args.get_kwargs() call should return False and args.dropout is then set to 0.

If this code is changed so that there is no reset of dropout, there seems to be a RuntimeError.

The masks for VariationalDropout are set for net and inp [here](https://github.com/princeton-vl/RAFT/blob/master/core/raft.py#L76).
However, right before the masks are applied here, inp is concatenated with the motion encoder [here](https://github.com/princeton-vl/RAFT/blob/master/core/modules/update.py#L160).

This means that the mask and the tensor are different sizes and will give the following RuntimeError.

  File "core/modules/update.py", line 34, in forward
    return self.mask * x
RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 1

Is this just a problem with the public facing github repo?

Best,
Charles

**Comment by zachteed** [comment]
Hi Charles,

Thank you for bringing this to my attention. I will look into this, but it looks like dropout was never actually used to train the networks. We will update the paper and the code if this ends up being the case.

**Comment by zachteed** [comment]
Hey Charles,

The pertrained models were not trained using dropout, which was why the default setting for dropout was 0. However, earlier I was experimenting with dropout, but it seems when I refactored the code for public facing repo I broke it and forget to test with dropout > 0. Anyways, dropout should be fixed now, thanks!
