### ISSUE TITLE
Features for Refinement

### ISSUE THREAD

**Issue by jasonfresh** [princeton-vl/RAFT#65]
Hi, I am curious about the input of the update block for the warping version in the ablation experiments.  would you give more details.
    1.  concat( fmap1, warp(fmap2, flow_pre) )
    2.  correlation( fmap1, warp(fmap2, flow_pre) )
I dont know which one you used and dose the warping version have pyramid?

for correlation pooling, have you try replace avg_pool with max_pooling

Thanks!

**Comment by zachteed** [comment]
Hi, we used #1, concatenating warped features with fmap1, no correlation.

I tried other forms of pooling like max and soft-plus but found average pooling to work best/

**Comment by jasonfresh** [comment]
Thanks for the reply!!
concatenating warped features with fmap1, the input channel of the next layer should be 256+256=512, is large than the (corr_windows**2)*corr_level=384. The total parameter number of network should increase. but the parameter number reduce from 4.8M to 2.8M in paper.

**Comment by zachteed** [comment]
Only a single feature extraction backbone was used in this experiment, instead of separating "context" and "feature" encoders.
