### ISSUE TITLE
which dataset you use in your pretrained model??

### ISSUE THREAD

**Issue by wildbrother** [princeton-vl/RAFT#67]

**Comment by zachteed** [comment]
We provide several different models:
raft-chairs: trained on FlyingChairs
raft-things: trained on FlyingChairs + FlyingThings
raft-sintel: trained on FlyingChairs + FlyingThings + Sintel + KITTI (this is the model which corresponds to our submission on the Sintel leaderboard)
raft-kitti: raft-sintel finetuned on only KITTI

Also, raft-small is trained on  FlyingChairs + FlyingThings
