### ISSUE TITLE
cannot load model

### ISSUE THREAD

**Issue by Singapore-mor** [princeton-vl/RAFT#71]
RuntimeError: D:\RAFT-master\models\raft_things.pth is a zip archive (did you mean to use torch.jit.load()?)

I cannot load the model?Any solutions? Thanks

**Comment by zachteed** [comment]
I'm guessing your using an older version of PyTorch (<1.6). You can download converted models which will work for earlier versions in #23

**Comment by Singapore-mor** [comment]
> I'm guessing your using an older version of PyTorch (<1.6). You can download converted models which will work for earlier versions in #23

Thanks a lot!
