### ISSUE TITLE
some question about Performance measurement

### ISSUE THREAD

**Issue by Allfu** [princeton-vl/RAFT#72]
Thank you for your wonderful work！

I would like to ask what is the performance measure of **Kitti-f1** mentioned in evaluate.py.
And, do 1px, 3px and 5px on Sintel represent the proportion of pixels with EPE < 1, EPE < 3 and EPE < 5 in the whole image?

Thanks!

**Comment by zachteed** [comment]
KITTI-Fl is the flow metric used on the KITTI leaderboard (<3px or <5% error) over all pixels. And yes, 1px, 3px and 5px on Sintel represent the proportion of pixels with EPE < 1, EPE < 3 and EPE < 5 in the whole image.

**Comment by Allfu** [comment]
Got it!
Thanks for your reply!
Thanks!
