### ISSUE TITLE
Question about the update operator

### ISSUE THREAD

**Issue by weihaosky** [princeton-vl/RAFT#73]
Hi, beautiful framework! I have some questions regarding the update operator.
1. I am confused about the times of update in training. In the experiments-implementation details, it says “unless otherwise noted, we evaluated after 32 flow updates on Sintel and 24 on KITTI” while in ablation study-inference updates, it says "although we unroll 12 updates during training". Does this mean in training it is 12 updates, and in inference for Sintel and KITTI it is 32 and 24?

2. I am not sure if I understand the weight tying correctly. For weight tying, in the code it is creating only one `self.update_block` and use it for every update. For not weight tying, in the code it is creating many `self.update_block`, e.g. for 12 updates there will be `self.update_block1` ~ `self.update_block12`. Every update uses a different update_block. Right?

Many thanks.

**Comment by zachteed** [comment]
Hi,
1. Yes that is correct. We unroll 12 updates during training and more during test time.  But results can be improved by using more updates during training (up to 24).
2. Yes, each instance of the update block has its own weights. To "untie" the weights you will need to create multiple updates blocks.
