### ISSUE TITLE
RAFT-3D

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [princeton-vl/RAFT#74]
Hi, are there any plans to release code for RAFT-3D as well?

**Comment by zachteed** [comment]
Yes, I will release the RAFT-3D code, but don't have an exact release date. Likely end of February at the latest.

**Comment by Maxzheng-tect** [comment]
hi, is RAFT_3D only support RGB-D as inputs?

**Comment by mehlls** [comment]
Hi! Thanks for your great work on RAFT and RAFT 3D! Do you have any update on publishing the 3D code?

**Comment by zachteed** [comment]
Hi, I'm working on preparing the code for release now. I'll provide pretrained models and inference code in the next week or two.
