### ISSUE TITLE
Minimum input image size?

### ISSUE THREAD

**Issue by Sino0904** [princeton-vl/RAFT#75]
Hello,

This might be a little naive question, but is there a minimum input image size that the network can handle? For example, when I tried demo.py to extract optical flow for images of size (64,64,3) The output optical flow was all Nan values.

Thanks!

**Comment by Guptajakala** [comment]
I met the same problem

**Comment by zachteed** [comment]
I tried the demo downsampling to 64x64. I didn't get Nan values, but the results were not very good, probably because the model was trained with a resolution 10x higher. I was able to get reasonable results down to a resolution of about 128x128.

**Comment by Sino0904** [comment]
I see. Do you think there is anything that can be done to get a good optical flow for images of sizes like (64,64)?

**Comment by wangbo-zhao** [comment]
I tried two images with 64*64 and I got nan too...But when I tried two random tensor , I did not get nan.  Maybe the model can not handle so little inputs.I think
