### ISSUE TITLE
Occlusions

### ISSUE THREAD

**Issue by zisismp4** [princeton-vl/RAFT#79]
Hello! Thank you for sharing your great work. I have recently started engaging with the optical flow concepts, so although your paper is great I can't figure out what happens with occlusions. How are occluded areas handled?
As far as my knowledge goes, occluded areas do not have a flow value. So, how do these pixels get filled?

**Comment by zachteed** [comment]
Hi, our network is usually able to estimate the optical flow for occluded regions using local context. For example, flow fields are usually spatially smooth so we can use information from surround pixels to essentially fill in the holes. 

If you look at the KITTI or Sintel leaderboards, they provide results for both occluded and non-occluded pixels.  The performance on the occluded pixels is usually somewhat worse than the non-occluded pixels.

**Comment by zisismp4** [comment]
In issue #57 you refer to cycle consistency in order to determine whether an area is occluded or not. Can you please explain how to examine the consistency?
I have tried to sum the flows for both directions, but this seems to be wrong, as the summing should be done in different locations for each flow. Can you please explain how to implement it correctly?

**Comment by zachteed** [comment]
Hi, the basic strategy is to estimate the forward flow F12 (I1->I2) and the backward flow F2(I2->I1).  Then for every pixel p

p' = F12(p) + p
p'' = p' + F21(p')

where F12(p) and P21(p') represent bilinear sampling. The consistency is given by the difference |p - p''|. Basically the forward flow should be consistent with the backward flow for non-occluded pixels.
