### ISSUE TITLE
Confusion about the represenation in the formula one

### ISSUE THREAD

**Issue by JiayuanSternLi** [princeton-vl/RAFT#8]
![image](https://user-images.githubusercontent.com/33815430/82642553-b19e4100-9c40-11ea-9001-731310c959c7.png)
it's a nice work, congratulations!
After going through the paper, I tried to understand the meaning of the formula one since it doesn't mention the definition of ijhkl.

I think (i, j) should be the coordinate of feature1, (k, l) should be the coordinate of feature2; h be the channel of feature1. However, all feature pairs should have the same number of channels. The formula is supposed to be:
C_ijkl = sum(g(I1)_ijh  *  g(I2)_klh)
instead of 
![image](https://user-images.githubusercontent.com/33815430/82643237-c0d1be80-9c41-11ea-83cb-abd70995c7a1.png)

The summation is over the channel, while img2 misses the channel representation. It doesn't make sense.

**Comment by zachteed** [comment]
Your correct this is a typo, C_ijkl = sum(g(I1)_ijh * g(I2)_klh) is the correct expression. Thank yo for pointing this out!

**Comment by JiayuanSternLi** [comment]
One more typo:
![image](https://user-images.githubusercontent.com/33815430/83127222-7a320780-a10c-11ea-96b2-ad7dfdf2efd1.png)
![image](https://user-images.githubusercontent.com/33815430/83127265-8a49e700-a10c-11ea-8b65-a309511721cc.png)
The denominator of Ck should be 2^(k-1)

**Comment by JiayuanSternLi** [comment]
The description in paper is inconsistent with the implementation. I don't think it as a fault but might cause confusion to readers
 
![image](https://user-images.githubusercontent.com/33815430/83128794-8028e800-a10e-11ea-9c2d-db5a05505f6b.png)

If we consider those RGB images as fmap1 fmap2, then the fmap2 is equivalent to C1. Then all things go well~ 
![image](https://user-images.githubusercontent.com/33815430/83129104-e57cd900-a10e-11ea-96a2-600695a44491.png)
