### ISSUE TITLE
Bilinear sampler bug

### ISSUE THREAD

**Issue by Alxead** [princeton-vl/RAFT#80]
Hi, thanks for sharing the code !
There seems to be a bug in `utils.py`. See below, the order of `xgrid` and `ygrid` is reversed. 

https://github.com/princeton-vl/RAFT/blob/224320502d66c356d88e6c712f38129e60661e80/core/utils/utils.py#L57-L62

In `CorrBlock`, `y` coordinate is before `x` coordinate grid.

I think the correct code is:
```
ygrid, xgrid = coords.split([1,1], dim=-1)
```

**Comment by vanderbilt2** [comment]
Hi, 
Is what you said related to the error I just posted? 
https://github.com/princeton-vl/RAFT/issues/83

I tried the change and didn't see improvement.
Thanks.

**Comment by Patrickwhj** [comment]
No, the x coordinate is before y coordinate.

https://github.com/princeton-vl/RAFT/blob/224320502d66c356d88e6c712f38129e60661e80/core/utils/utils.py#L74-L77

Instead, the order of `dy` and `dx` should be switched in `Corrblock`, though it yields the same result

https://github.com/princeton-vl/RAFT/blob/224320502d66c356d88e6c712f38129e60661e80/core/corr.py#L35-L39

**Comment by zachteed** [comment]
Yeah, I use the (x, y) convention so the bilinear-sampler is consistent. There isn't a bug in the bilinear-sampler (swapping the order of the coordinates gives very bad results).
