### ISSUE TITLE
Running on 1 GPU

### ISSUE THREAD

**Issue by AliKafaei** [princeton-vl/RAFT#81]
Hi,
First, I congrats for your valuable and elegant work.
I wanted to run it on one GPU (Titan V with 12 Gb memory) to evaluate just one pair of images. However, I found out of memory and the slower extension you provided did not help. 
What should I do to use the pre-trained model on one GPU?
Regards,
Ali

**Comment by zachteed** [comment]
Hi Ali, I would recommend using the ./train_mixed.sh schedule which uses a single GPU for training. Even though the Titan V GPU doesn't have tensor cores, mixed precision training will still significantly reduce memory requirements.

**Comment by AliKafaei** [comment]
Hi, Thank you for your response. You mentioned that train-mixed is especially designed for RTX series. Does it work on other single GPUs?
Another point is that I want to use the network in evaluation mode (use pre-train weights). What should I do on that case?
I used the following code for importing the network
#########################
parser = argparse.ArgumentParser()
parser.add_argument('--model', help="restore checkpoint")
parser.add_argument('--path', help="dataset for evaluation")
parser.add_argument('--small', action='store_true', help='use small model')
parser.add_argument('--mixed_precision', action='store_true', help='use mixed precision')
parser.add_argument('--alternate_corr', action='store_true', help='use efficent correlation implementation')
args = parser.parse_args()
args.alternate_corr=True
model = torch.nn.DataParallel(raft.RAFT(args))
A=torch.load('models/raft-things.pth')

model.load_state_dict(A)
model = model.module
model=model.cuda()
##################################
But I think there would be a more efficient way to do that.
Regards,
Ali

**Comment by zachteed** [comment]
Yes, it will still work for other GPUs, you just won't get a speed improvement that you would with an RTX. 

The demo.py script gives an example of how to a apply a pretrained network. Also, the evaluation.py file shows how a trained model can be evaluated on KITTI, Sintel, and FlyingChairs. Your code wil work fine, you just need to set the model to evaluation mode
model.eval()
