### ISSUE TITLE
RuntimeError: grid_sampler()

### ISSUE THREAD

**Issue by vanderbilt2** [princeton-vl/RAFT#83]
Hi, does anybody encounter the following error?

While trying to run evaluation, upon passing two frames in the resolution 1024-by-436 to model, it reports the following error (on some other test frames, I was able to run no problem, thus I suspect it was image-resolution problem, but not sure): 

"
  flow_low, flow_up = model(frame_1, frame_2, iters=20, test_mode=True)
  File "...\conda\py36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "RAFT/core\raft.py", line 125, in forward
    corr = corr_fn(coords1) # index correlation volume
  File "RAFT/core\corr.py", line 45, in __call__
    corr = bilinear_sampler(corr, coords_lvl)
  File "RAFT/core\utils\utils.py", line 66, in bilinear_sampler
    img = F.grid_sample(img, grid, align_corners=True)
  File "...\conda\py36\lib\site-packages\torch\nn\functional.py", line 3391, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected grid and input to have same batch size, but got input with sizes [7040, 1, 55, 128] and grid with sizes [6912, 9, 9, 2]

"

**Comment by zachteed** [comment]
The image dimensions need to be divisible by 8. You can use the InputPadder class as used in evaluation.py and demo.py
```
padder = InputPadder(image1.shape)
image1, image2 = padder.pad(image1[None].cuda(), image2[None].cuda())
```

**Comment by vanderbilt2** [comment]
Thank you.
