### ISSUE TITLE
Training a model in Self-supervised manner

### ISSUE THREAD

**Issue by antoniopavlis** [princeton-vl/RAFT#84]
Hi, congrats on your work !
I'm interested in the possibility of self-supervised learning of your RAFT model. What learning procedure would you recommend in that case.

**Comment by zachteed** [comment]
Hi, I haven't done any experiments with self-supervised flow so I can't really give any advice. But maybe some of the self-supervised techniques used in this paper: [https://arxiv.org/abs/2006.04902] could be used with the RAFT architecture.
