### ISSUE TITLE
Small update block doesn't have the attribute "reset_mask"

### ISSUE THREAD

**Issue by JiayuanSternLi** [princeton-vl/RAFT#9]
Hi, 

When doing inference using your small RAFT, it runs into error:
![image](https://user-images.githubusercontent.com/33815430/82775865-91a69180-9e7b-11ea-8f3b-e0a0b9972548.png)
![image](https://user-images.githubusercontent.com/33815430/82775847-86ebfc80-9e7b-11ea-95a7-46e15724519c.png)

After copying and pasting these lines from basicupdateblock to smallupdateblock, no errors:
![image](https://user-images.githubusercontent.com/33815430/82775919-c1559980-9e7b-11ea-93b5-1caf04a8a70f.png)

**Comment by zachteed** [comment]
Thanks! It should be fixed now. It seems I introduced some errors in the dropout when refactoring the code.
