### ISSUE TITLE
Different size between optical flow and original image when running demo.py

### ISSUE THREAD

**Issue by ReekiLee** [princeton-vl/RAFT#96]
Hello!
  Thanks for your great work firstly~
  I have a question about sizes of image and optical flow. When I run demo.py, the input size of demo-frames file is (436, 1024, 3), and after padding it becomes (440, 1024, 3), I wonder why only height pads. Finally the output size is (440, 1024, 2), same height and width as padding, but different from input image.
  Is it the correct output? How could I get the optical flow which has the same size as input?
  Thank you in advance!

**Comment by zachteed** [comment]
Hi, the input images are padded so that the dimensions are divisible by 8. You can call unpad to restore the dimensions:
```
  image1, image2 = padder.pad(image1[None].cuda(), image2[None].cuda())
  _, flow_pr = model(image1, image2, iters=iters, test_mode=True)
  flow = padder.unpad(flow_pr[0])
```

**Comment by ReekiLee** [comment]
It helps me a lot. Thank you @zachteed 
Another question is about the Inference Updates. The paper says "Although we unroll 12 updates during training, we can
apply an arbitrary number of updates during inference". Why? Do the arbitary number of updates have the same parameters?

**Comment by zachteed** [comment]
Yeah that's correct, the update operator has shared weights for each iteration
