### ISSUE TITLE
Gray scale image.

### ISSUE THREAD

**Issue by JerolSOIBAM** [princeton-vl/RAFT#97]
The demo.py works fine for any RGB files but. When I try running some grayscale image it throws an error stating a number of dimensions don't match in permute. However, I see in the training dataset there are grayscale images for example in training-occlusions-bamboo_1. Are you using this image while training or not? If not does this mean that I have to train the model for grayscale images. 
Thanks!

**Comment by zachteed** [comment]
Hi, you should try repeating the last dimension of the the grayscale image by modifying the load_image function. 
```
def load_image(imfile):
    img = np.array(Image.open(imfile)).astype(np.uint8)
    if len(img.shape) == 2:
        img = np.stack([img, img, img], axis=-1)
    img = torch.from_numpy(img).permute(2, 0, 1).float()
    return img[None].to(DEVICE)

```

It usually works fine for grayscale images, the network just expects 3 channels as input
