### ISSUE TITLE
Dataset order for training schedule

### ISSUE THREAD

**Issue by SamriddhiJain** [princeton-vl/RAFT#99]
Hi

Thanks for sharing the work, it is very helpful.

Could you share your reasonings behind the order in which datasets (C, T, S, K) are used to train the model. For my application I started training from scratch directly with T and found that learning curve plateaus at 1px score of 0.72, 5px score of 0.85. I suspect this is because FlyingThings3D is relatively a difficult dataset to train on as compared to Chairs. But I was wondering if you have seen similar behaviour while experimentation and can give some more insights. 

Thanks.

**Comment by zachteed** [comment]
Hi, we followed the dataset schedule that was proposed by FlowNet2 and used by a bunch of other recent optical flow papers.  However, I did find that skipping the first stage (training on Chairs) didn't really hurt the validation performance on Sintel or KITTI by too much, maybe about 5-10% worse EPE. 

The numbers you are getting are close to what I've seen. FlyingThings is a difficult dataset with very extreme motions so the results will be naturally worse than Sintel or FlyingChairs. You can probably get slightly better results by extending the training schedule to 160k steps or so.

**Comment by askerlee** [comment]
@zachteed Hi Zach, thanks for sharing the amazing work! Happy to see you are still around answering questions. Just begin to play with optical flow, and my question is: when you train on flyingthings, did you use the subset used by flownet2 ("DispNet/FlowNet2.0 dataset subsets" in the data webpage)? or the whole dataset? Thanks.
